### ISSUE TITLE
What makes it no RTOS?

### ISSUE THREAD

**Issue by bmcdonnell-ionx** [janjongboom/mbed-os-example-blinky-no-rtos#1]
Could you add verbiage to the `README` to indicate what exactly causes it to build without the OS? Is it just the fact that you have `mbed-os/rtos/` (and its dependents) in the `.mbedignore` file, or is there something else?

Does it work the same (still build without the OS) if you `mbed export` the project and build it with an IDE?

Any other gotchas, like is it significant that you have `"platform.stdio-flush-at-exit": false` in your `target_overrides` in `mbed_app.json`?

Thanks.

**Comment by janjongboom** [comment]
Hi, yes, it's just removing rtos folder for now (and other stuff that completely depends on RTOS). The flush at exit was required before, but no longer is. Will remove. Thanks!

**Comment by janjongboom** [comment]
Landed and updated to Mbed OS 5.9 here: https://github.com/janjongboom/mbed-os-example-blinky-no-rtos/commit/ec0267beaf9211e7891f73cf8da8908eddb1a574
